version: "3"
services:
  node:
    build:
      context: ./
      dockerfile: ./node/NodeServer.Dockerfile
    image: nebula/node
    ports:
      - "9199:9199"
    cap_add:
      - ALL
    network_mode: "host"
    environment:
      - NSERVER=localhost:9190
  server:
    build:
      context: ./
      dockerfile: ./server/NebulaServer.Dockerfile
    image: nebula/server
    ports:
      - "9190:9190"
    # We're using this for performance profiling NET_ADMIN, SYS_ADMIN
    # remove it in final production.
    cap_add:
      - ALL
    environment:
      # can be a S3 file like s3://nebula/cluster-dev.yml
      - NCONF=/etc/nebula/configs/cluster.yml
    network_mode: "host"
  web:
    build:
      context: ./
      dockerfile: ./http/web.Dockerfile
    image: nebula/web
    ports:
      - "8088:8088"
    network_mode: "host"
    environment:
      # can be a S3 file like s3://nebula/cluster-dev.yml
      - NS_ADDR=localhost:9190
